language: c
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8']
      env: COMPILER=gcc-4.8

script:
  - cd unix/gcc
  - make rebuild CC=$COMPILER